services:
  golang-app:
    build: .
    container_name: basic-golang-api
    ports:
      - "8082:8080"  # Expose port 8080 to the host machine
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
